# kubelet workaround
---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata: 
  labels: 
    machineconfiguration.openshift.io/role: master
  name: 99-kubelet_internal_checkpoint
spec: 
  config:
    ignition: 
      config: 
        replace: 
          verification: {}
      proxy: {}
      security: 
        tls: {}
      timeouts: {}
      version: 3.2.0
    passwd: {}
    systemd:
      units:
      - contents: |
          [Unit]
          Description=Delete /var/lib/kubelet/device-plugins/kubelet_internal_checkpoint
          Before=kubelet.service
          [Service]
          Type=oneshot
          ExecStart=/bin/bash -c '/bin/rm /var/lib/kubelet/device-plugins/kubelet_internal_checkpoint'
        name: delete-file.service
        enabled: true